/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RemedialCRUDTraining;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    //what the fuck
}
